# Generated by Django 5.2.8 on 2026-01-01 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('cancelled', 'Cancelled')], default='finished', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_per_question', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizzes.topic')),
            ],
            options={
                'db_table': 'live_session',
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('socket_id', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.session')),
            ],
            options={
                'db_table': 'live_session_participant',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_appearances', to='quizzes.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='live.session')),
            ],
            options={
                'db_table': 'live_session_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_answers', to='quizzes.answeroption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='live.session')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='live.sessionparticipant')),
                ('session_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='live.sessionquestion')),
            ],
            options={
                'db_table': 'live_session_answer',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['teacher', 'status'], name='live_sessio_teacher_3742db_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['finished_at'], name='live_sessio_finishe_1fca46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionquestion',
            unique_together={('session', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionanswer',
            unique_together={('participant', 'session_question')},
        ),
    ]
